# Generated by Django 5.1.3 on 2024-11-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_alter_address_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='departement',
            field=models.CharField(blank=True, choices=[('Ouest', 'ouest'), ('Sud', 'sud'), ('Nord', 'nord'), ('Nord-Est', 'nord-est'), ('Nord-Ouest', 'nord-ouest'), ('Centre', 'centre'), ('Sud-Est', 'sud-est'), ('Artibonite', 'artibonite'), ('Grande-Anse', 'grande-anse'), ('Nippes', 'nippes')], max_length=100, null=True),
        ),
    ]
